sam -sing -speed 40 -pitch 35 -phonetic RAOAOAO
sam -sing -speed 40 -pitch 26 -phonetic SIYIYIYIYIY
sam -sing -speed 40 -pitch 35 -phonetic YAAAAAAAAAAAA
sam -sing -speed 32 -pitch 31 -phonetic SVYAA
sam -sing -speed 40 -pitch 28 -phonetic SHEHEHEHEHN
sam -sing -speed 40 -pitch 41 -phonetic NAAAAAAAA
sam -sing -speed 40 -pitch 41 -phonetic YAAAAAAAA
sam -sing -speed 40 -pitch 31 -phonetic NAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 35 -phonetic SHAAAAAAAA
sam -sing -speed 40 -pitch 39 -phonetic DEHR
sam -sing -speed 40 -pitch 35 -phonetic ZHAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 52 -phonetic VAAAAAA
sam -sing -speed 40 -pitch 52 -phonetic RAOAOS
sam -sing -speed 40 -pitch 46 -phonetic SIYIYIYIYIY
sam -sing -speed 40 -pitch 46 -phonetic YAAAAAAAAAAAA
sam -sing -speed 40 -pitch 41 -phonetic LYUW
sam -sing -speed 40 -pitch 39 -phonetic BIYIYIYIYIYIYIYIY
sam -sing -speed 40 -pitch 39 -phonetic MAAAAAAAAAA
sam -sing -speed 40 -pitch 35 -phonetic YAAAA
sam -sing -speed 40 -pitch 31 -phonetic NAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 28 -phonetic SHAAAA
sam -sing -speed 40 -pitch 26 -phonetic STRXAA
sam -sing -speed 40 -pitch 23 -phonetic NAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 35 -phonetic MAOAOAO
sam -sing -speed 40 -pitch 21 -phonetic GUWUWUWUWUW
sam -sing -speed 40 -pitch 23 -phonetic CHAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic YAAAA
sam -sing -speed 40 -pitch 23 -phonetic VAOAOAOAOAOAO
sam -sing -speed 40 -pitch 28 -phonetic LYAAAAAA
sam -sing -speed 40 -pitch 35 -phonetic VEHEHEHEH
sam -sing -speed 40 -pitch 26 -phonetic LIYIYIYIYIYIYIYIYIY
sam -sing -speed 40 -pitch 28 -phonetic KAAAAAAAA
sam -sing -speed 40 -pitch 31 -phonetic YAAAA
sam -sing -speed 40 -pitch 28 -phonetic SLAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 41 -phonetic VAAAAAA
sam -sing -speed 40 -pitch 41 -phonetic TVAOAO
sam -sing -speed 40 -pitch 31 -phonetic EHEHEHEHEHEHEHEHEHEHEHEHEHEHEH
sam -sing -speed 40 -pitch 35 -phonetic DAOAOAOAOAO
sam -sing -speed 40 -pitch 39 -phonetic STAO
sam -sing -speed 40 -pitch 35 -phonetic YAAAAAAAAAAN
sam -sing -speed 40 -pitch 52 -phonetic EHEHEHEHEHEHEHEH
sam -sing -speed 40 -pitch 52 -phonetic NAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic VSEHEHEHEH
sam -sing -speed 40 -pitch 28 -phonetic VREHEHEHEH
sam -sing -speed 40 -pitch 31 -phonetic MEHEH
sam -sing -speed 40 -pitch 35 -phonetic NAAAAAAAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 21 -phonetic SLAAAAAAAAAAAAV
sam -sing -speed 40 -pitch 23 -phonetic SYAAAA
sam -sing -speed 40 -pitch 26 -phonetic AAAAAAAAAA
sam -sing -speed 40 -pitch 28 -phonetic AOAOAOAOAO
sam -sing -speed 40 -pitch 26 -phonetic AOAOAOAOAO
sam -sing -speed 40 -pitch 23 -phonetic TEHEHEHEHEHEHEHEHEHEHEHEH
sam -sing -speed 40 -pitch 35 -phonetic CHEHEHS
sam -sing -speed 40 -pitch 35 -phonetic TVAOAOAOAOAOAOAOAOAO
sam -sing -speed 40 -pitch 26 -phonetic NAAAAAAAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 28 -phonetic SHEHEHEHEH
sam -sing -speed 40 -pitch 31 -phonetic EHEHEHEHEHEH
sam -sing -speed 40 -pitch 35 -phonetic SVAOAOAO
sam -sing -speed 40 -pitch 31 -phonetic AOAOAOAOAO
sam -sing -speed 40 -pitch 28 -phonetic BAOAOAOAOAOAOAO
sam -sing -speed 40 -pitch 41 -phonetic DNAOAO
sam -sing -speed 40 -pitch 41 -phonetic EYEYEYEYEYEY
sam -sing -speed 40 -pitch 26 -phonetic BRAAAAAAAAAA
sam -sing -speed 31 -pitch 31 -phonetic SKIY/X
sam -sing -speed 40 -pitch 28 -phonetic NAAAA
sam -sing -speed 40 -pitch 26 -phonetic RAOAOAOAOAOAO
sam -sing -speed 31 -pitch 31 -phonetic DAOV
sam -sing -speed 40 -pitch 28 -phonetic SAO
sam -sing -speed 40 -pitch 26 -phonetic YUWUWUWUWUWUWUWZ
sam -sing -speed 40 -pitch 31 -phonetic VEHEHEHEH
sam -sing -speed 40 -pitch 26 -phonetic KAOAOAO
sam -sing -speed 39 -pitch 19 -throat 20 -mouth 128 -phonetic VAOAOAOAOAOAOAOAOAOIY
sam -sing -speed 40 -pitch 21 -phonetic PREHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEH
sam -sing -speed 40 -pitch 21 -phonetic DKAAAAAAAO
sam -sing -speed 40 -pitch 23 -phonetic AAAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic MIYIYIYIY
sam -sing -speed 40 -pitch 23 -phonetic IYIYIYIYIYIYIYIYIYIYIYIYIYIY
sam -sing -speed 40 -pitch 21 -phonetic DAAAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic NAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 23 -phonetic MUWUWUWUWUWUWUWUWUWUW
sam -sing -speed 40 -pitch 26 -phonetic DRXAOAO
sam -sing -speed 40 -pitch 28 -phonetic AAAAAAAAAA
sam -sing -speed 40 -pitch 31 -phonetic S IX*
sam -sing -speed 40 -pitch 28 -phonetic NAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic RAOAOAOAOAOAOAO
sam -sing -speed 40 -pitch 31 -phonetic NAAAAAAAA
sam -sing -speed 40 -pitch 31 -phonetic YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 26 -phonetic SLAAAAAAAA
sam -sing -speed 40 -pitch 28 -phonetic SYAAAAAAAA
sam -sing -speed 22 -pitch 31 -phonetic STRXAA
sam -sing -speed 40 -pitch 35 -phonetic NAAAAAAAAAAAAAA
sam -sing -speed 40 -pitch 52 -phonetic MUXUXUXUXUXUX
sam -sing -speed 40 -pitch 52 -phonetic GAOR
sam -sing -speed 40 -pitch 26 -phonetic DIYMIYIYIYIYIY
sam -sing -speed 70 -pitch 28 -phonetic SYAAAAAAAA
sam -sing -speed 60 -pitch 31 -phonetic TAOAOAOAOAOAOAOAO
sam -sing -speed 80 -pitch 26 -phonetic BAOIYIYIYIYIYIYIYIYIYIYIYIY
/
/